### ISSUE TITLE
Just closes after installing, cant find it anywhere.

### ISSUE THREAD

**Issue by SnoweFox** [xaduha/Combat-Demo-Downloader#2]
So i'm wondering it is just not working now, or what? I downloaded, extracted, started the installation, and after it finishes, it just closes. I looked through all my folders, cant find it anywhere. Anyone had this issue?

**Comment by xaduha** [comment]
It downloads to the same folder where the executable is located. There should be a new folder named COMBAT_TUTORIAL_DEMO
